# Generated by Django 4.2.16 on 2024-11-30 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_rename_customuser_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], default=None, help_text='The gender of user', max_length=10, null=True),
        ),
    ]
