# Generated by Django 4.2.16 on 2025-01-26 17:32

from django.db import migrations, models
import user.utils


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_alter_user_dietary_restrictions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='health_conditions',
            field=models.JSONField(blank=True, default=list, help_text='Health conditions of user', validators=[user.utils.validate_health_conditions]),
        ),
        migrations.AlterField(
            model_name='user',
            name='streak',
            field=models.PositiveIntegerField(blank=True, default=0, help_text='User streak', null=True),
        ),
    ]
