# Generated by Django 4.2.16 on 2024-11-30 17:46

from django.db import migrations, models
import multiselectfield.db.fields
import recipes.utils


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('quantity', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('food_name', models.CharField(max_length=255)),
                ('preparation_time', models.CharField(max_length=100)),
                ('cooking_time', models.CharField(max_length=100)),
                ('total_time', models.CharField(max_length=100)),
                ('course', models.CharField(max_length=100)),
                ('cuisine', models.CharField(max_length=100)),
                ('servings', models.IntegerField()),
                ('calories', models.IntegerField(blank=True, null=True)),
                ('preparation_instructions', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to=recipes.utils.recipe_image_path)),
                ('mood', models.CharField(choices=[('happy', 'Happy'), ('stressed', 'Stressed'), ('relaxed', 'Relaxed')], default='happy', max_length=20)),
                ('weather', models.CharField(choices=[('sunny', 'Sunny'), ('rainy', 'Rainy'), ('cloudy', 'Cloudy')], default='sunny', max_length=20)),
                ('energy', models.CharField(choices=[('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], default='low', max_length=20)),
                ('hunger', models.CharField(choices=[('snack', 'Snack'), ('meal', 'Meal'), ('full', 'Full')], default='snack', max_length=20)),
                ('budget', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('very high', 'Very High')], default='low', max_length=20)),
                ('dietary', multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('vegetarian', 'Vegetarian'), ('vegan', 'Vegan'), ('gluten-free', 'Gluten-Free'), ('dairy-free', 'Dairy-Free')], max_length=39)),
                ('allergies', multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('nuts', 'Nuts'), ('dairy', 'Dairy'), ('eggs', 'Eggs'), ('soy', 'Soy')], max_length=19)),
                ('ingredients', models.ManyToManyField(to='recipes.ingredient')),
            ],
        ),
    ]
