# Generated by Django 4.2.16 on 2024-10-29 17:59

from django.db import migrations, models
import recipes.utils


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=recipes.utils.recipe_image_path),
        ),
    ]
