# Generated by Django 4.2.16 on 2024-11-06 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_recipe_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='mood',
            field=models.CharField(choices=[('happy', 'Happy'), ('stressed', 'Stressed'), ('relaxed', 'Relaxed')], default='happy', max_length=20),
        ),
        migrations.AddField(
            model_name='recipe',
            name='weather',
            field=models.CharField(choices=[('sunny', 'Sunny'), ('rainy', 'Rainy'), ('cloudy', 'Cloudy')], default='sunny', max_length=20),
        ),
    ]
