# Generated by Django 4.2.16 on 2024-11-06 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_recipe_mood_recipe_weather'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='energy',
            field=models.CharField(choices=[('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], default='low', max_length=20),
        ),
    ]
