# Generated by Django 4.2.16 on 2024-11-06 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0004_recipe_energy'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='hunger',
            field=models.CharField(choices=[('snack', 'Snack'), ('meal', 'Meal'), ('full', 'Full')], default='snack', max_length=20),
        ),
    ]
