# Generated by Django 4.2.16 on 2024-11-06 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0005_recipe_hunger'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='budget',
            field=models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('very high', 'Very High')], default='low', max_length=20),
        ),
    ]
