# Generated by Django 4.2.16 on 2024-11-06 14:29

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0006_recipe_budget'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='allergies',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('nuts', 'Nuts'), ('dairy', 'Dairy'), ('eggs', 'Eggs'), ('soy', 'Soy')], max_length=19),
        ),
        migrations.AddField(
            model_name='recipe',
            name='dietary',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('vegetarian', 'Vegetarian'), ('vegan', 'Vegan'), ('gluten-free', 'Gluten-Free'), ('dairy-free', 'Dairy-Free')], max_length=39),
        ),
    ]
